psfinaki/CheckYourCzech

src/Core/SequenceExtensions.fs
src/Core/Storage.fs
src/Server/WebServer.fs

Details and reasons are in the task. Basically, this will allow to do us client filtering after Azure filtering, e.g.
```fsharp
// gender = 'hrad'
// patterns = '["růže","píseň"]'
let patternFilter (noun: NounPlural.NounPlural) = noun.Pattern.Contains patternFromQuery
let noun = tryGetRandom<NounPlural.NounPlural> "nounplurals" [genderFilter] [patternFilter]
```

Introduced Azure Table Storage post filtering (#537)

---

src/Scraper/Properties/launchSettings.json

This allows to debug Scraper in VS without any additional actions (like commenting code out or set env vars in some cmd externally).

Minor improvement for the local dev

---

.paket/Paket.Restore.targets
package.json
yarn.lock

This fixes some awesome bug with webpack on Windows, as described [here](https://github.com/JeffreyWay/laravel-mix/issues/2153). The only real change is in `package.json`, everything else is regenerated.

Fixed webpack dependency issue

---

.gitignore
package.json
src/Client/template.html
src/Client/webpack.config.js
yarn.lock

This finally fixes the css flickering. 
So now we want to load styles in different ways in dev and prod. In dev we want to have a js script to inject the raw styles into the page after it loads (a faster way, with page flickering), and in prod we want to have css file properly referenced (a slower way, without page flickering).
This means we better do not have a hardcoded `index.html` file because it is hard to set it up to work in both modes properly. Instead, we are now generating it based on the `template.html`. The difference between versioned `template.html` and generated `index.html` is currently only in presence of the scripts at the end of the file, although in the future this method will also allow us to do things like cache busting and minification for html.
The guy that …

Fixed css loading in webpack production mode (#548)

---

.gitignore
src/Client/webpack.common.js
src/Client/webpack.development.js
src/Client/webpack.production.js

This basically leverages webpack's cache busting [capabilities](https://webpack.js.org/guides/caching/). Now we include the file content hash in the name of static resources. If any change is made, the hash will be completely different and it will force browsers to request the new version of the resource from the server. 
If we don't do it, browsers can take file content from the cache and prevent users from seeing real changes made.

Implemented cache busting (#553)

---

build.fsx
src/Client/webpack.development.js

This includes easier and faster way to open browser (via webpack options instead of separate process), removing some default values (e.g. [inline](https://webpack.js.org/configuration/dev-server/#devserverinline)) and unneeded values (e.g. [historyApiFallback](https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback)).

Minor improvements for webpack dev server

---

src/Core/NeuterNounPatternDetector.fs

I guess I accidentally changed the pattern detector while some experiments there. Therefore words relevant words were assigned "okno" pattern whereas the API still asked for "město" pattern.

Fixed bug with the město pattern

---

tests/Core.IntegrationTests/NounTests.fs

Yesterday somebody filled in the gender for the _trosečník_ article in the wiki and broke our test :D
This is another article making the test pass.

Corrected a test

---

.paket/Paket.Restore.targets
src/Client/resources.js
src/Client/webpack.common.js

It looks like a [more canonical way](https://stackoverflow.com/questions/35322958/can-i-use-webpack-to-generate-css-and-js-separately) for webpack is to load styles as resources. It also helps to avoid generating and referencing unneeded js files with styles.

Fixed generation of redundant style.js (#564)

---

src/Client/pages/NounAccusatives.fs
src/Client/pages/NounPlurals.fs
src/Core/NeuterNounPatternDetector.fs
tests/Core.IntegrationTests/NeuterNounPatternDetectorTests.fs

This is a relatively easy pattern to add, its detection is quite easy. Detection code is based on what is written [in official grammar](http://prirucka.ujc.cas.cz/?slovo=drama#nadpis2_8).
Tests are added. Also, there was some obsolete, unused and wrong function `getPattern`, I removed it.

Added the Drama pattern to neuters (#530)

---

src/Core/NeuterNounPatternDetector.fs
tests/Core.IntegrationTests/NeuterNounPatternDetectorTests.fs

Okay, so looks like checking nominatives and accusatives was not enough because there are words like [pyžama](http://prirucka.ujc.cas.cz/?slovo=py%C5%BEama), which are neuter and have "ma" in both those cases but don't belong do the Drama pattern. 
Here is an improved pattern detection algorithm.

Improved Drama pattern detection (#530)

---

src/Core/Article.fs
src/Core/Core.fsproj
src/Core/Declensions.fs
src/Core/FeminineNounPatternDetector.fs.fs
src/Core/GrammarCategories.fs
src/Core/MasculineAnimateNounPatternDetector.fs
src/Core/MasculineInanimateNounPatternDetector.fs
src/Core/NeuterNounPatternDetector.fs
src/Core/Noun.fs
src/Core/NounAccusative.fs
src/Core/NounCategories.fs
src/Core/NounPlural.fs
src/Core/WikiDeclensions.fs
tests/Core.IntegrationTests/DeclensionsTests.fs

Examples and details are given in the related task.
This is what's happening in the PR:
1) Two modules are extracted from the `Declensions` module: `NounCategories` (just noun properties) and `WikiDeclensions` (logic of extracting declensions from wiki for all currently known possible structure of the page)
2) `IsIndeclinable` and `hasDeclension` functions now utilize the new `getChildrenPartsWhen` function which returns true both for single and multiple _skloňování_ sections
3) `getDeclension` function in the `Declensions` module now collects the results from all the declensions section
4) Two tests for that are added, I also ran Scraper locally to verify that now it does record such words to the database

Handling nouns with multiple declensions (#573)

---

src/Client/webpack.development.js
src/Server/Program.fs

Server is changed according to [Saturn](https://saturnframework.org/docs/api/application/#force_ssl) docs, dev server side is changed according to the [webpack](https://webpack.js.org/configuration/dev-server/#devserverproxy) docs.
This way HTTPS is indeed forced (I deployed the app to the test slot) whereas locally things still work.

Forcing HTTPS for the service (#578)

---

src/Common/Conjugation.fs
src/Core/Validation/AdjectiveValidation.fs
src/Core/Validation/NounValidation.fs
src/Core/Validation/VerbValidation.fs
src/Server/Tasks/Verb.fs
src/WikiParsing/Articles/AdjectiveArticle.fs
src/WikiParsing/Articles/Article.fs
src/WikiParsing/Articles/NounArticle.fs
src/WikiParsing/Articles/VerbArticle.fs
src/WikiParsing/Html.fs
tests/WikiParsing.Tests/ArticleTests.fs

This is an attempt for a framework on top of the `Article` framework :D 
The API allows to easily go through Wikipedia article sections. I have tried various options, this is the best I could come up with for now. The API _match_, _matches_, _isMatch_ is inspired by the [Regex API](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=netframework-4.8#methods). 
I have tried extending the API so that we don't have to call `hasInfo` and `getInfo` methods of the `Article` module, but it brought more mess than value, partly because there are not enough occurrences to properly generalize the code. In the end, the `Article` framework got some recursion and some simplification of terms. I added some tests for the new methods as well. 
I would like to think this …

Simplified article scanning (#266)

---

arm-template-appinsights.json
src/Server/Server.fsproj

Microsoft [deprecated](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/monitoring-classic-retirement) classic App Service alerts (which we use to get emails about exceptions and failures in the service). That broke our deployment therefore we have to change our ARM template to deploy new generation alerts.
Also, starting with ASP .NET Core 2.2, IIS supports [in-process hosting model](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#in-process-hosting-model), which is kind of latest and greatest, and it looks like recently with some later 3.0.x version this is how the app tries to run by default. 
However, most probably due to our free tier limitations, we cannot run apps like this (thereby app just does not start) so we now need to …

Deployment updates due to changes in Azure internals

---

src/WikiParsing/Articles/Article.fs
tests/WikiParsing.Tests/ArticleTests.fs

The idea is to one day make the framework robust and independent and decoupled from everything else here. For that, we should not assume that the framework functions are called in some specific order.
This is a small step in that direction - `getPart` function now returns an option therefore one does not have to call `hasPart` before it.
Tests are adjusted.

Minor optimization of the Article framework

---

src/Client/pages/NounAccusatives.fs
src/Client/pages/NounPlurals.fs
src/Core/Nouns/MasculineInanimateNounPatternDetector.fs
tests/Core.IntegrationTests/MasculineInanimateNounPatternDetectorTests.fs

[This pattern](http://prirucka.ujc.cas.cz/?slovo=rytmus#nadpis2_3) is more complicated to detect than others. The pattern addresses imported words (from Latin or Greek) ending with "us", "es", "os". But words ending like that can be either just Czech (_nos_, _les_) or completely "czechified" and following "hrad" pattern despite their origin (_bonus_, _citrus_). 
Other words (e.g. _glóbus_) allow multiple declensions, by "hrad" and by "rytmus".

 Added the Rytmus pattern to masculine inanimates (#533)

---

src/Scraper/App.fs
src/Scraper/Word.fs
src/WikiParsing/Articles/Article.fs
tests/Core.IntegrationTests/AdjectiveValidationTests.fs
tests/Core.IntegrationTests/FeminineNounPatternDetectorTests.fs
tests/Core.IntegrationTests/Helper.fs
tests/Core.IntegrationTests/MasculineAnimateNounPatternDetectorTests.fs
tests/Core.IntegrationTests/MasculineInanimateNounPatternDetectorTests.fs
tests/Core.IntegrationTests/NeuterNounPatternDetectorTests.fs
tests/Core.IntegrationTests/NounValidationTests.fs
tests/Core.IntegrationTests/VerbValidationTests.fs
tests/WikiParsing.Tests/AdjectiveArticleTests.fs
tests/WikiParsing.Tests/ArticleTests.fs
tests/WikiParsing.Tests/Helper.fs
tests/WikiParsing.Tests/NounArticleTests.fs
tests/WikiParsing.Tests/VerbArticleTests.fs

So back in a day there was a [discussion](https://github.com/psfinaki/CheckYourCzech/pull/622#pullrequestreview-348370725) to reuse `HttpClient` for Scraper but back then it was hard to do because of multiple places where the app communicated with the internet.
After recent optimizations, for every word the app accesses Wiki only once. So it is much easier to inject single `HttpClient` for all the calls. The actual change is the first three files, everything else is adjustments in tests.
As per my amateur benchmarks, this change actually makes quite a difference - in average the app  processes 3.7x more words and tests run 20% faster.

Reusing HttpClient within Scraper (#623)

---

src/Common/StringHelper.fs
src/WikiParsing/WikiString.fs
tests/WikiParsing.Tests/WikiParsing.Tests.fsproj
tests/WikiParsing.Tests/WikiStringTests.fs

The original motivation was to handle forms like `abdikuji (hovorově: abdikuju)` (see the [task](https://github.com/psfinaki/CheckYourCzech/issues/646)). 
However adjusting existing logic there was significantly decreasing clarity of what was going on. So I decided to rewrite the framework via regex and recursion. The code also has small domain type `Form`.
Most of the code in the framework is private now and that allowed tests to be more representative, having real Wiki forms there as inputs and what we expect from them as outputs.
I have run Scraper with this logic for a couple of hours, parsed forms look alright.

Improved WikiString framework (#646)

---

src/Common/Common.fsproj
src/Common/Conjugation.fs
src/Common/Exercises.fs
src/Scraper/WordRegistration/AdjectiveRegistration.fs
src/Scraper/WordRegistration/NounRegistration.fs
src/Scraper/WordRegistration/VerbRegistration.fs
src/Server/Tasks/Adjective.fs
src/Server/Tasks/Noun.fs
src/Server/Tasks/Utils.fs
src/Server/Tasks/Verb.fs
src/Storage/Defaults.fs
src/Storage/ExerciseModels/AdjectiveComparative.fs
src/Storage/ExerciseModels/AdjectivePlural.fs
src/Storage/ExerciseModels/BaseEntity.fs
src/Storage/ExerciseModels/NounAccusative.fs
src/Storage/ExerciseModels/NounPlural.fs
src/Storage/ExerciseModels/VerbConjugation.fs
src/Storage/ExerciseModels/VerbImperative.fs
src/Storage/ExerciseModels/VerbParticiple.fs
src/Storage/Reflection.fs
src/Storage/Storage.fs
src/Storage/Storage.fsproj

The idea is to have exercise models in terms of the domain types. They are now in the Common/Exercises module.
The translation to Azure Table Storage types (which are limited to string, bool and a few others) is done at the very end via attributes so that the entity modules look more clear and succinct.
The reflection magic is done in `BaseEntity` and is inspired by this [article](https://blog.bitscry.com/2019/04/12/adding-complex-properties-of-a-tableentity-to-azure-table-storage/). Everything else is repetitive - no business logic is needed.

More robust exercise models (#652)

---

src/Common/Exercises.fs
src/Common/GrammarCategories.fs
src/Scraper/Word.fs
src/Scraper/WordRegistration/NounRegistration.fs
src/Server/Tasks/Noun.fs
src/Storage/Defaults.fs
src/Storage/ExerciseModels/Noun.fs
src/Storage/Storage.fsproj

So we are moving to the next exercise where users can decline nouns for all the cases.
Here are mostly the backend changes - new table, new model and so on. The correct validation was already there. For now I did not remove anything to not mess up the PR but this will be the next step.
Minor frontend changes include retrieving results from the new table. The case filters are added so that we get only those nouns that have the cases that we need.

Generalized noun declension exercise - backend (#653)

---

src/Common/GrammarCategories.fs
src/WikiParsing/Articles/NounArticle.fs

It turned out what I though to be a case DU is actually a enum ([related SO question](https://stackoverflow.com/a/10384098/3232646)). Enums are worse for pattern matching, so I redid things a little bit.

Changed case enum to case union

---

src/Core/Nouns/FeminineNounPatternDetector.fs
src/Core/Nouns/MasculineAnimateNounPatternDetector.fs
src/Core/Nouns/MasculineInanimateNounPatternDetector.fs
src/Core/Nouns/NeuterNounPatternDetector.fs
src/Core/Nouns/Noun.fs
src/Core/Nouns/NounPatterns.fs
src/Scraper/WordRegistration/NounRegistration.fs
src/WikiParsing/Articles/NounArticle.fs
tests/Core.IntegrationTests/FeminineNounPatternDetectorTests.fs
tests/Core.IntegrationTests/MasculineAnimateNounPatternDetectorTests.fs
tests/Core.IntegrationTests/MasculineInanimateNounPatternDetectorTests.fs
tests/Core.IntegrationTests/NeuterNounPatternDetectorTests.fs
tests/WikiParsing.Tests/NounArticleTests.fs

Pattern detectors now accept `Declension` instead of the whole wiki article. That makes code and dependencies more clear - we only need a declension table to understand the pattern.
No logic is changed otherwise, basically adjustments in noun registration and tests.

Simplified noun pattern detection (#673)

---

src/Common/Exercises.fs
src/Scraper/ExerciseCreation/Adjectives.fs
src/Scraper/ExerciseCreation/Nouns.fs
src/Scraper/ExerciseCreation/Verbs.fs
src/Scraper/WordRegistration/AdjectiveRegistration.fs
src/Scraper/WordRegistration/NounRegistration.fs
src/Scraper/WordRegistration/VerbRegistration.fs
src/Storage/Defaults.fs
src/Storage/ExerciseModels/AdjectiveComparative.fs
src/Storage/ExerciseModels/AdjectivePlural.fs
src/Storage/ExerciseModels/Noun.fs
src/Storage/ExerciseModels/VerbConjugation.fs
src/Storage/ExerciseModels/VerbImperative.fs
src/Storage/ExerciseModels/VerbParticiple.fs

Types in `Exercises` are meant to match what users see when doing exercises whereas Id is a storage concept. So Id is now generated during word registration, right before writing to database.

Removed Ids from exercise models (#678)

---

src/Client/Pages/VerbImperatives.fs
src/Client/Widgets/Class.fs
src/Common/Conjugation.fs
src/Common/Exercises.fs
src/Common/Verbs.fs
src/Core/Verbs/ConjugationPatternDetector.fs
src/Core/Verbs/VerbClasses.fs
src/Storage/Defaults.fs
tests/Core.Tests/VerbClassesTests.fs

Renamed `Pattern` to `ParticiplePattern` (because that's what it about as opposed to `ConjugationPattern`), moved `VerbClass` to `Conjugation` module (but some further cleanup in grammar categories will be probably needed).

Minor cleanup in verb categories

---

src/Client/Pages/VerbConjugation.fs
src/Common/Exercises.fs
src/Scraper/ExerciseCreation/Verbs.fs
src/Server/Tasks/Verb.fs
src/Storage/Defaults.fs
src/Storage/ExerciseModels/VerbConjugation.fs

After all the refactoring and cleanup with verb patterns, I realized that we are using wrong patterns for the conjugation exercise. We should use class and conjugation patterns there, instead of very specific participle patterns that work only for making participle form.

Fixed pattern in the conjugation exercise (#688)

---

src/Client/Client.fsproj
src/Client/Pages/NounDeclension.fs
src/Client/Widgets/Case.fs
src/Client/Widgets/Number.fs
src/Client/scss/task.scss
src/Common/Utils.fs
src/Server/Tasks/Noun.fs

So we are making the declension exercise even more granular and more useful.
The interface is still to be tweaked I guess - but this is a relatively non-invasive and functional change.

Added an option to select a particular case for declension (#691)

---

src/WikiParsing/Articles/NounArticle.fs
src/WikiParsing/NounWikiDeclension.fs
src/WikiParsing/WikiParsing.fsproj
tests/WikiParsing.Tests/NounArticleTests.fs

The idea is to collect all the cases in one go, instead of initializing type providers for each case. Thanks to this, tests now run approximately 4-5x faster (mostly because of those for noun pattern detection).
I moved all type provider related work to a separate module, `NounWikiDeclension`. It works on its own type, `WikiDeclension`, which is basically raw strings from wiki. Then in `NounArticle` we convert that to our domain type `Declension`, which contains parsed and distinct forms, possibly from multiple tables.

Optimized declension extraction (#699)

---

src/Common/Exercises.fs
src/Scraper/ExerciseCreation/Nouns.fs
src/Server/Tasks/Noun.fs
src/Storage/Defaults.fs
src/Storage/ExerciseModels/Noun.fs

This is related to the fact that when parsing Wiktionary we already know the canonical form of the noun (that's the title of the article) so we better propagate it rather than "forget" it and figure it out again on the upper level. 
That will be also similar to "infinitive" for conjugation, it is just that declension does not have such a nice term for the canonical form (e.g. [lemma](https://en.wikipedia.org/wiki/Lemma_(morphology)), which seams less clear to me).

Minor model adjustment

---

src/Client/Client.fsproj
src/Client/Pages/AdjectiveComparatives.fs
src/Client/Pages/AdjectivePlurals.fs
src/Client/Pages/NounAccusatives.fs
src/Client/Pages/NounDeclension.fs
src/Client/Pages/NounPlurals.fs
src/Client/Pages/VerbConjugation.fs
src/Client/Pages/VerbImperatives.fs
src/Client/Pages/VerbParticiples.fs
src/Client/Utils.fs
src/Client/Widgets/Task.fs

When updating Fable, I accidentally changed the way promises work in the app, and the code for loading tasks started to execute for every event (including any key press). This fixes that behavior.
Basically we are not passing around `fun _ -> Fetch.fetchAs(url, decoder)` instead of `Fetch.fetchAs(url, decoder)`.

Fixed extra requests during exercises (#709)

---

src/WikiParsing/AdjectiveWikiParsing.fs
src/WikiParsing/Articles/AdjectiveArticle.fs
src/WikiParsing/ConcreteArticles.fs
src/WikiParsing/WikiParsing.fsproj
tests/WikiParsing.Tests/AdjectiveArticleTests.fs

I want to create a new exercise for general adjective declension and for that we need to take all the cases from wiki.
I implemented it in similar fashion to what we have with nouns: created a separate module (`AdjectiveWikiParsing`) doing just parsing stuff and integrated it into `AdjectiveArticle`.

Parsing all cases for adjective declension (#717)

---

src/WikiParsing/Articles/VerbArticle.fs

Copypaste issue - calling `WikiString` framework too early.

Fixed processing of multiple participle forms (#727)

---

src/Common/GrammarCategories/Verbs.fs
src/Common/WikiArticles.fs
src/Scraper/ExerciseCreation/Verbs.fs
src/Storage/Defaults.fs
src/WikiParsing/Articles/VerbArticle.fs
tests/WikiParsing.Tests/VerbArticleTests.fs

That's basically for `WikiArticles` types to look uniform.

Refactoring: several code alignments around verbs

---

src/Client/Utils.fs
src/Client/Widgets/Task.fs
src/Server/Tasks/Adjective.fs
src/Server/Tasks/Noun.fs
src/Server/Tasks/Utils.fs
src/Server/Tasks/Verb.fs

A few improvements on client-server interaction:
1) Different responses in case of found and not found, seems like [idiomatic way](https://github.com/search?l=F%23&q=return%21+RequestErrors.NOT_FOUND&type=Code) in F#
2) More native type for task (record instead of class)

More idiomatic server responses

---

src/Client/Pages/NounDeclension.fs
src/Client/Widgets/Case.fs
src/Client/Widgets/Class.fs
src/Client/Widgets/Gender.fs
src/Client/Widgets/Number.fs
src/Client/Widgets/Pattern.fs
src/Client/Widgets/Regularity.fs
src/Client/scss/task.scss

closes #147 
Centered as per link in issue, works for me in Chrome.
Also fixed display on mobile - too many filters were stacking up in a line
After fix:

centered display + mobile filter fix

---

src/Client/scss/task.scss

closes #661 
unchanged in case of short questions. In case the line is filled in it wraps on the next one like that:

fixed long label issue

---

src/Scraper/ConsoleLogger.fs
src/Scraper/Logging.fs

Looks like latest .NET Core cannot automatically infer this code so I added some clarifications for the compiler.

Adjustments in console logging

---

tests/Client.UiTests/Tests.fs

Otherwise pipeline hangs after running them (even successfully).

More graceful exit for the UI tests

---

CheckYourCzech.sln
arm-template.json
deployment/Deployment/Deployment.fsproj
deployment/Deployment/Infrastructure.fs
deployment/Deployment/Program.fs
deployment/Deployment/paket.references
paket.dependencies
paket.lock

So now we have the `Deployment` project with the `Infrastructure` module instead of the most part of the `arm-template.json`. A small part of it still stays as Farmer does not support all the Application Insights settings that we need. They are plugged in via `link_to_unmanaged_app_insights` in the `webApp` of `Infrastructure`.
In general yes this is much better and concise than raw json. Azure Pipelines are adjusted.

Introducing Farmer (#754)

---

deployment/Deployment/paket.references
paket.dependencies
paket.lock
src/Core/paket.references
src/Scraper/paket.references
src/Storage/paket.references
tests/Client.UiTests/paket.references
tests/Core.IntegrationTests/paket.references
tests/Core.Tests/paket.references
tests/WikiParsing.Tests/paket.references

`FSharp.Core` nuget package is implicitly referenced with the framework ([1](https://fsharp.github.io/FSharp.Compiler.Service/corelib.html), [2](https://devblogs.microsoft.com/dotnet/announcing-f-5/#comment-8100)) so we don't need to specify it explicitly (as we need framework versions anyway).

Removed redundant FSharp.Core reference in dependencies

---

azure-pipelines.yml

closes #517.
The pipeline has duplication because it's meant to barely replace whatever we have now in "Releases" (which has duplication). Also, I want to move to deployment slots instead of parallel deployments, so this will be modified anyway.

Using YAML pipeline for releases (#517)

---

azure-pipelines.yml
deployment/Deployment/Infrastructure.fs

closes #784 
This is fully automated deployment - we first deploy the "exp" slot, then run the UI tests and then go to production. Slot is created "manually" via Azure CLI because there is no Farmer support for this yet.
Also, to have slots we need to be in the Standard tier, so this also changes. This should be cheaper than having to Basic webs though.

Moving to deployment slots instead of two webs (#784)
