psfinaki/CheckYourCzech

- src/Core/Letters.fs
- tests/Core.IntegrationTests/FeminineNounPatternDetectorTests.fs
Yet another vowel missing in the list of vowels
> Improve píseň pattern detection (#541)

- src/Core/Noun.fs
- tests/Core.IntegrationTests/NounTests.fs
The correct and used `isIndeclinable` function is the `Declensions` module now.
> Removed unused code

- src/Core/Noun.fs
- src/Core/NounAccusative.fs
- src/Core/NounPlural.fs
- tests/Core.Tests/NounTests.fs
The issue is described in the related task, technically just another filter for noun validation. Added a couple of tests for that as well.
> Filtering out noun reflexive deverbal nouns (#576)

- src/Core/Declensions.fs
- tests/Core.IntegrationTests/DeclensionsTests.fs
Now checking both "noun" (_podstatné jméno_) and "declensions" (_skloňování_) sections.
> Improved indeclinability check (#581)

- src/Core/Noun.fs
- tests/Core.IntegrationTests/NounTests.fs
> Checking indeclinability prior to pattern detection (#583)

- src/Client/pages/NounAccusatives.fs
- src/Client/pages/NounPlurals.fs
- src/Core/Nouns/MasculineAnimateNounPatternDetector.fs
- tests/Core.IntegrationTests/MasculineAnimateNounPatternDetectorTests.fs
Yeah so that's a bummer, the name of the pattern was wrong :D
> Change pan noun pattern to pán (#591)

- src/Client/pages/NounAccusatives.fs
- src/Client/pages/NounPlurals.fs
- src/Client/pages/VerbImperatives.fs
- src/Client/widgets/Class.fs
- src/Core/ExerciseModels/VerbImperative.fs
- src/Core/Storage.fs
- src/Core/Verbs/Verb.fs
- src/Core/Verbs/VerbClasses.fs
- src/Core/Verbs/VerbPatternDetector.fs
- tests/Core.Tests/VerbClassesTests.fs
- tests/Core.Tests/VerbPatternDetectorTests.fs
I made DU for the verb classes as discussed in one of the recent PRs.
Finally I decided to give them some names which is better than numbers. Names refer to the verb ending in the third person singular, as per the [official grammar](https://cs.wikipedia.org/wiki/%C4%8Cesk%C3%A1_slovesa#Slovesn%C3%A9_t%C5%99%C3%ADdy_a_vzory).
> DU for the verb classes (#590)

- src/WikiParsing/Articles/Article.fs
- src/WikiParsing/Html.fs
- tests/Core.IntegrationTests/NounValidationTests.fs
> Handling nouns with multiple `rod` entries on the page (#601)

- .paket/Paket.Restore.targets
- src/Scraper/Scraper.fsproj
- tests/Core.IntegrationTests/Core.IntegrationTests.fsproj
- tests/Core.Tests/Core.Tests.fsproj
- tests/WikiParsing.Tests/WikiParsing.Tests.fsproj
Apart from acquiring new .NET [capabilities](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0), this will also allow us to simplify our build pipelines.
> Updated .NET Core version across projects

- src/Client/pages/NounAccusatives.fs
- src/Client/pages/NounPlurals.fs
- src/Core/Nouns/NeuterNounPatternDetector.fs
- tests/Core.IntegrationTests/NeuterNounPatternDetectorTests.fs
As per rules [here](http://prirucka.ujc.cas.cz/?slovo=muzeum#nadpis3_2).
> Muzeum pattern for neuter nouns (#532)

- src/Core/Storage.fs
- src/Scraper/Word.fs
- src/Server/Tasks/Adjective.fs
- src/Server/Tasks/Noun.fs
- src/Server/Tasks/Verb.fs
Okay so I have finally read how to write async code in F#! Things look quite smooth.
Actually, rewriting things properly (e.g. calling `Async.RunSynchronously` only at the root of the execution) brings some performance benefits as well - we now write to different Azure tables in parallel.
> Properly using Azure Storage async API (#299)

- src/Server/Tasks/Noun.fs
- src/Server/WebServer.fs
So this is the server part of the exercise, the new endpoint.
The fronted is coming, but this is how the response can be displayed:
> Generalize noun declension exercise - server (#656)

- src/Client/App.fs
- src/Client/Client.fsproj
- src/Client/Pages.fs
- src/Client/pages/Home.fs
- src/Client/pages/NounDeclension.fs
- src/Client/widgets/Navbar/View.fs
This is the new page - I put the (beta) label that we can remove after removing "Noun Plurals" and "Noun Accusatives".
Together with the Server part looks like this:
> Generalized noun declension exercise - frontend (#658)

- src/Core/Validation/NounValidation.fs
- src/Server/Tasks/Noun.fs
- tests/Core.IntegrationTests/NounValidationTests.fs
> Registering plurale tantum nouns (#662)

- src/Common/Common.fsproj
- src/Common/Declension.fs
- src/Common/Exercises.fs
- src/Common/GrammarCategories.fs
- src/Common/WikiArticles.fs
- src/Core/Nouns/FeminineNounPatternDetector.fs
- src/Core/Nouns/MasculineAnimateNounPatternDetector.fs
- src/Core/Nouns/MasculineInanimateNounPatternDetector.fs
- src/Core/Nouns/NeuterNounPatternDetector.fs
- src/WikiParsing/Articles/NounArticle.fs
Moved declension to `Declension` because I want to add some more declension-related stuff there.
> Rearranged grammar categories a bit

- src/Common/Declension.fs
- src/Common/Exercises.fs
- src/Common/StringHelper.fs
- src/Core/Nouns/FeminineNounPatternDetector.fs
- src/Core/Nouns/MasculineAnimateNounPatternDetector.fs
- src/Core/Nouns/MasculineInanimateNounPatternDetector.fs
- src/Core/Nouns/NeuterNounPatternDetector.fs
- src/Core/Nouns/NounPatterns.fs
- src/Storage/Defaults.fs
- src/Storage/ExerciseModels/Noun.fs
- src/Storage/Serialization.fs
- src/Storage/Storage.fsproj
> Using types for noun declension patterns (#682)

- src/Core/Nouns/NounPatterns.fs
I just get stressed when lines are longer than half of the Github diff :)
(technically this is also a more robust way to do things in terms of compile checks for `Gender` union extension - but it is not likely for the new gender to happen :D)
> Minor refactoring

- tests/Core.Tests/ConjugationPatternDetectorTests.fs
> Improve and extended conjugation pattern testing (#693)

- src/Scraper/Scraper.fsproj
- src/Server/Server.fsproj
- tests/Core.IntegrationTests/Core.IntegrationTests.fsproj
- tests/Core.Tests/Core.Tests.fsproj
- tests/WikiParsing.Tests/WikiParsing.Tests.fsproj
.NET Framework 2.1 is coming separately :)
> Updating to .NET Core 3.1 (#671)

- .vscode/launch.json
- .vscode/tasks.json
- build.fsx
These new things can be leveraged to debug the whole app in VS Code as described [here](https://safe-stack.github.io/docs/feature-debugging/).
> Simplified full stack debugging (#711)

- src/Client/Pages/NounAccusatives.fs
- src/Client/Pages/NounDeclension.fs
- src/Client/Pages/NounPlurals.fs
- src/Common/Declension.fs
- src/Core/Nouns/MasculineAnimateNounPatternDetector.fs
- tests/Core.IntegrationTests/MasculineAnimateNounPatternDetectorTests.fs
Yet another minor pattern pf masculine animates.
> Add the Dinosaurus pattern to masculine animates (#534)

- src/Common/Exercises.fs
- src/Common/WikiArticles.fs
- src/Scraper/ExerciseCreation/Adjectives.fs
- src/Scraper/WordRegistration/AdjectiveRegistration.fs
- src/Storage/Defaults.fs
- src/Storage/ExerciseModels/AdjectiveDeclension.fs
- src/Storage/Storage.fsproj
- src/WikiParsing/Articles/AdjectiveArticle.fs
- src/WikiParsing/Articles/NounArticle.fs
- tests/WikiParsing.Tests/AdjectiveArticleTests.fs
Now, as we parse all the declension forms, we can put them in the related table.
> Created a table for adjective declension (#719)

- src/WikiParsing/Articles/AdjectiveArticle.fs
- src/WikiParsing/Articles/NounArticle.fs
- src/WikiParsing/Raw/Adjective.fs
- src/WikiParsing/Raw/Noun.fs
- src/WikiParsing/WikiParsing.fsproj
This is just a small change to uniform two modules for parsing raw wiki data.
> Cleanup: raw wiki parsing

- src/Client/Widgets/Case.fs
- src/Client/Widgets/Number.fs
- src/Common/Common.fsproj
- src/Common/GrammarCategories/Common.fs
- src/Common/GrammarCategories/Nouns.fs
- src/Server/Tasks/Adjective.fs
- src/Server/Tasks/Noun.fs
- src/Server/WebServer.fs
This also includes a minor rearrangement of grammar categories - now as case and number is needed for adjectives as well, I moved them to the shared module.
> Backend part for adjective declension (#723)

- src/WikiParsing/Articles/VerbArticle.fs
- src/WikiParsing/ConcreteArticles.fs
- src/WikiParsing/Raw/Verb.fs
- src/WikiParsing/WikiParsing.fsproj
- tests/WikiParsing.Tests/VerbArticleTests.fs
Similar to `Raw.Adjective` and `Raw.Noun`.
> Refactoring: split verb raw wiki parsing logic to a separate module

- src/Common/StringHelper.fs
- src/Core/Core.fsproj
- src/Core/Numerals/NumberToWords.fs
- src/Core/Numerals/Numbers.fs
- src/Core/Numerals/Triplet.fs
- src/Core/Numerals/TripletToWords.fs
- src/Server/Server.fsproj
- src/Server/Tasks/Numeral.fs
- src/Server/WebServer.fs
- tests/Core.Tests/Core.Tests.fsproj
- tests/Core.Tests/Numerals/NumberToWordsTests.fs
- tests/Core.Tests/Numerals/TripletToWordsTests.fs
Building words for numbers is quite complicated to do entirely correct (see the task description). 
One useful concept I used to organize the code is `Triplet` - a number with at most 3 digits. Generally, there is some recursive logic about building words here, slicing triplet by triplet from the number and adding concatenating wordings.
Heavy testing included.
> Added backend for the Cardinals exercise (#741)

- src/Client/App.fs
- src/Client/AppPages.fs
- src/Client/Client.fsproj
- src/Client/Pages/Home.fs
- src/Client/Pages/NumeralCardinals.fs
- src/Client/Pages/NumeralsCardinals.fs
- src/Client/Widgets/Gender.fs
- src/Client/Widgets/NumeralRange.fs
- src/Client/scss/colors.scss
- src/Client/scss/home.scss
- src/Common/Common.fsproj
- src/Common/Numerals.fs
- src/Server/Tasks/Numeral.fs
- tests/WikiParsing.Tests/WikiStringTests.fs
closes #745 
Task display:
Available ranges are: 0+ (Any), 0-100, 100-1000, 1000-1000000, 1000000+
Main page was modified either:
> Cardinals task with a filter

- src/Core/Numerals/TripletToWords.fs
- tests/Core.Tests/Numerals/TripletToWordsTests.fs
Too much copypaste - stumbled upon exceptions in wording for 14 and 19 🤦
> Fixed the writing for exceptional numbers in the second ten

- build.fsx
Polished a few things after recent changes, see comments as well. Tried all the targets locally, seem to work.
> Refactoring in the build script

- src/Client/Widgets/Task.fs
- tests/Client.UiTests/Tests.fs
> Trimming answers (#758)

- .config/dotnet-tools.json
- deployment/Deployment/Deployment.fsproj
- deployment/Deployment/Infrastructure.fs
- src/Scraper/App.fs
- src/Scraper/ConsoleLogger.fs
- src/Scraper/Program.fs
- src/Scraper/Scraper.fsproj
- src/Server/Program.fs
- src/Server/Server.fsproj
- src/Server/Tasks/Adjective.fs
- src/Server/Tasks/Noun.fs
- src/Server/Tasks/Verb.fs
- tests/Client.UiTests/Client.UiTests.fsproj
- tests/Client.UiTests/Tests.fs
- tests/Core.IntegrationTests/Core.IntegrationTests.fsproj
- tests/Core.Tests/Core.Tests.fsproj
- tests/WikiParsing.Tests/WikiParsing.Tests.fsproj
Client will be moved separately as the process might be more complicated because of the fable-compiler.
> Moving Server and Scraper to .NET5 & F#5 (#763)

- src/Client/Client.fsproj
`Common` is enough, we don't need `Core` here.
> Simplified dependencies for Client

- build.fsx
> Removed raw yarn commands from the build script (#767)

- CheckYourCzech.sln
- deployment/Deployment/Deployment.fsproj
- src/Client/Client.fsproj
- src/Core/Core.fsproj
- src/Scraper/Scraper.fsproj
- src/Server/Server.fsproj
- src/Storage/Storage.fsproj
- src/WikiParsing/WikiParsing.fsproj
- tests/Client.UiTests/Client.UiTests.fsproj
- tests/Core.IntegrationTests/Core.IntegrationTests.fsproj
- tests/Core.Tests/Core.Tests.fsproj
- tests/WikiParsing.Tests/WikiParsing.Tests.fsproj
I guess in VS Code by default one sees all the files but this is different in VS
> Added some non-f# files to the solution and projects for convenience

- .config/dotnet-tools.json
- .gitignore
- build.fsx
- package.json
- src/Client/webpack.common.js
- src/Common/Utils.fs
- yarn.lock
This is pure Fable update, without introduction of F#5 and anything else. We did not have many troubles, only two functions needed to be inlined.
closes #770
> Moving to Fable 3 (#770)

- build.fsx
closes #778 
Tested all the targets on fresh clones.
> Simplified build script + added tool restore (#778)

- src/Common/StringHelper.fs
- src/Core/Adjectives/ComparativeBuilder.fs
- src/Core/Numerals/Numbers.fs
- src/Core/Verbs/ConjugationPatternDetector.fs
- src/Core/Verbs/ParticipleBuilder.fs
- src/Server/Tasks/Numeral.fs
- src/Storage/ExerciseModels/BaseEntity.fs
- src/Storage/Serialization.fs
- src/Storage/Storage.fs
- src/WikiParsing/Articles/NounArticle.fs
- src/WikiParsing/WikiString.fs
> Applying string interpolation from F# 5

- CheckYourCzech.sln
- azure-pipelines.yml
This was super easy eventually, there is an option "Export to YAML" in the build menu, and it works.
> Converted build pipeline to YAML (#517)
